name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup rust
      uses: dtolnay/rust-toolchain@stable
    - name: configure cache
      uses: Swatinem/rust-cache@v2
    - name: build
      run: cargo build --verbose --lib
    - name: test
      run: cargo test --verbose --lib